# Generated by Django 4.1.7 on 2023-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='api.socialmediaprofile'),
        ),
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='api.socialmediaprofile'),
        ),
    ]
