# Generated by Django 4.1.7 on 2023-03-17 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_alter_socialmediaprofile_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediaprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socialmediaprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
