# Generated by Django 4.1.7 on 2023-03-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_socialmediaprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='socialmediaprofile',
        ),
    ]
