# Generated by Django 4.1.7 on 2023-03-17 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_delete_socialmediaprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='socialmediaprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ManyToManyField(blank=True, related_name='user_followers', to='api.socialmediaprofile')),
                ('following', models.ManyToManyField(blank=True, related_name='user_following', to='api.socialmediaprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='socialmediaprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
